import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Terms of Service - StreetSweep',
};

export default function TermsOfServicePage() {
    return (
        <main className="max-w-3xl mx-auto px-6 py-12 text-gray-800">
            <h1 className="text-3xl font-bold mb-2">Terms of Service</h1>
            <p className="text-sm text-gray-500 mb-8">Last updated: September 27, 2026</p>

            <p className="mb-6">
                These Terms of Service ("Terms") govern your use of StreetSweep (the
                "Service"). By using StreetSweep, you agree to these Terms.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-2">Description of Service</h2>
            <p className="mb-6">
                StreetSweep helps cyclists and runners find and route streets they
                haven't covered yet, using map data (OpenStreetMap) and, optionally,
                your connected Strava or Ride with GPS activity history.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-2">Accounts &amp; Connected Services</h2>
            <p className="mb-6">
                You may sign in using a third-party provider (e.g. Google, Strava). You
                are responsible for maintaining the security of your account and any
                connected third-party accounts. StreetSweep is not responsible for the
                availability, accuracy, or content of third-party services it integrates
                with.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-2">Acceptable Use</h2>
            <ul className="list-disc pl-6 space-y-2 mb-6">
                <li>Don't use the Service for any unlawful purpose.</li>
                <li>Don't attempt to disrupt, overload, or gain unauthorized access to the Service or its infrastructure.</li>
                <li>Don't scrape or bulk-extract data from the Service beyond your own account's data.</li>
            </ul>

            <h2 className="text-xl font-semibold mt-8 mb-2">Routing Is Informational Only</h2>
            <p className="mb-6">
                Routes generated by StreetSweep are provided for informational and
                planning purposes only. Road conditions, closures, traffic laws, and
                safety hazards change constantly and may not be reflected in the
                underlying map data. You are solely responsible for your own safety and
                for obeying all applicable traffic laws while using any route generated
                by the Service.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-2">No Warranty</h2>
            <p className="mb-6">
                The Service is provided "as is" and "as available," without warranties of
                any kind, express or implied, including but not limited to accuracy,
                completeness, or fitness for a particular purpose.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-2">Limitation of Liability</h2>
            <p className="mb-6">
                To the fullest extent permitted by law, StreetSweep and its operator
                shall not be liable for any indirect, incidental, or consequential
                damages, including injury, arising from your use of the Service or any
                route it generates.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-2">Termination</h2>
            <p className="mb-6">
                We may suspend or terminate your access to the Service at any time,
                including for violation of these Terms. You may stop using the Service
                and request deletion of your account at any time.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-2">Changes to These Terms</h2>
            <p className="mb-6">
                We may update these Terms from time to time. Continued use of the
                Service after changes take effect constitutes acceptance of the revised
                Terms.
            </p>

            <h2 className="text-xl font-semibold mt-8 mb-2">Contact Us</h2>
            <p className="mb-6">
                Questions about these Terms? Contact us at{' '}
                <a href="mailto:chadbeaudin@gmail.com" className="text-blue-600 underline">
                    chadbeaudin@gmail.com
                </a>.
            </p>
        </main>
    );
}
